name: Check new releases

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 8 * * *'

jobs:
  check_release:
    name: Checking new releases on docker hub
    runs-on: ubuntu-latest
    outputs:
      php_version: ${{ steps.split.outputs.php_version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Scan Docker Repository
        uses: dhet/scan-docker-tags-action@v1.0.1
        with:
          image: library/php
          max-age-minutes: 1440 # 1 day in minutes
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          tag-regex: \d+\.\d+\.\d+$
        id: scan

      - name: Print
        run: "echo 'Recent updates: ${{ steps.scan.outputs.tags }}'"

      - uses: actions/setup-go@v2
        with:
          go-version: '1.16.1' # The Go version to download (if necessary) and use.

      - id: split #php_version_json
        run: echo "::set-output name=php_version::$(go run split.go ${{ steps.scan.outputs.tags }})"

  docker_hub:
    uses: 3lever/php/.github/workflows/publish_docker_hub.yml@master
    needs: check_release
    if: ${{needs.jobs.check_release.steps.split.outputs.php_version}}
    with:
      php_version: ${{ needs.check_release.outputs.php_version }}
    secrets:
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}