name: Publish image on docker hub

on:
  workflow_dispatch:
    inputs:
      php_versions:
        description: 'Choose the php version that you want to apply for example: ["8.1.3"]'
        required: true
  workflow_call:
    inputs:
      php_versions:
          type: string
          required: true
    secrets:
      DOCKERHUB_USERNAME:
          required: true
      DOCKERHUB_TOKEN:
          required: true

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php_version: ${{ fromJSON(inputs.php_versions || github.event.inputs.php_versions) }}
        variant: [ 'fpm', 'cli' ]
        data_base: [ 'postgresql', 'mysql' ]
        base_sufix: [ '', '-dev' ]
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: shieldwalll/php:${{ env.PHP_VERSION }}-${{ matrix.data_base }}${{ matrix.base_sufix }}
          build-args: |
            PHP_VERSION=${{ env.PHP_VERSION }}
            BASE_SUFIX=${{ matrix.base_sufix }}
          target: base-${{ matrix.data_base }}
        env:
          PHP_VERSION: ${{matrix.php_version}}-${{matrix.variant}}
