name: Publish image on docker hub

on:
  workflow_dispatch:
    inputs:
      php_version:
          description: 'Choose the php version that you want to apply for example: 8.1'
          required: true

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        variant: [ 'fpm', 'cli' ]
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: 3lever/php:${{ env.PHP_VERSION }}-${{matrix.variant}}-postgresql
          build-args: "PHP_VERSION=${{ env.PHP_VERSION }}-${{matrix.variant}}"
        env:
          PHP_VERSION: ${{ github.event.inputs.php_version }}
