name: Publish image on docker hub

on:
  workflow_call:
    inputs:
      php_version:
          description: 'Choose the php version that you want to apply for example: 8.1'
          type: string
          required: true
    secrets:
        dockerhub_username:
          required: true
        dockerhub_token:
          required: true

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php_version: ${{ fromJSON(inputs.php_version) }}
        variant: [ 'fpm', 'cli' ]
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.dockerhub_username }}
          password: ${{ secrets.dockerhub_token }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: 3lever/php:${{ env.PHP_VERSION }}-postgresql
          build-args: "PHP_VERSION=${{ env.PHP_VERSION }}"
        env:
          PHP_VERSION: ${{matrix.php_version}}-${{matrix.variant}}
